name: Android CI

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure gradlew is executable
        run: chmod +x android/gradlew

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Branch specific builds
      - name: Build Android (Dev apk)
        if: github.ref == 'refs/heads/dev'
        run: yarn buildAndroidDevApk

      - name: Build Android (Staging apk)
        if: github.ref == 'refs/heads/staging'
        run: yarn buildAndroidStagingApk

      - name: Build Android (Prod apk and Bundle)
        if: github.ref == 'refs/heads/main'
        run: yarn buildAndroidProdApkAndBundle

      # Locate and upload outputs
      - name: Locate APKs/Bundles
        run: |
          echo "🔍 Searching for APKs and AABs..."
          find android/app/build/outputs -type f \( -name "*.apk" -o -name "*.aab" \) || true

      - name: Upload APK/AAB artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: |
            android/app/build/outputs/**/*.apk
            android/app/build/outputs/**/*.aab
